apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-hub.fullname" . }}-secret
  labels:
    {{- include "agent-hub.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  keycloak-client-secret: {{ default "" .Values.backend.env.KEYCLOAK_CLIENT_SECRET | b64enc | quote }}
